// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ovavfgrirtucttdopawu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92YXZmZ3JpcnR1Y3R0ZG9wYXd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTQ5NjEsImV4cCI6MjA2NTQ3MDk2MX0.T1AtEfTCJ7a1T8eKfxUl8ckgfIdQtL93ycxaa8peo4E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);